---
- name: Delete EC2 key pair {{ key_pair_name }}
  ec2_key:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    name: "{{ key_pair_name }}"
    region: "{{ key_pair_region }}"
    state: absent
  register: aws_key_pair

- name: Delete EC2 key pair PEM file
  file:
    dest: "~/.ssh/{{ key_pair_name }}.pem"
    state: absent
...
