---
- name: Get EC2 Instance facts
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ ec2_instance_region | default(aws_region) }}"
    filters:
      "tag:Name": "{{ ec2_instance_name | upper }}"
      "instance-state-name": "running"
  register: ec2_instance_facts
...
